[package]
edition = "2021"
name = "bload_oath"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
dev = ["bevy/dynamic"]
web = []

[dependencies]
bo_logging = { path = "bo_logging/" }
bo_pathfinding = { path = "bo_pathfinding/" }

# Core Crates
bracket-terminal = "^0.8.5"
bracket-noise = "^0.8.2"
bracket-geometry = { version = "^0.8.3", features = ['serde'] }
bracket-color = { version = "^0.8.2", features = ['serde'] }
bracket-random = { version = "^0.8.2", features = ['serde'] }

iyes_loopless = { git = "https://github.com/iyesgames/iyes_loopless", branch = "bevy_main" }
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }

# Utility Crates
parking_lot = { version = "^0.12.1", features = ["nightly"] }
serde = { version = "^1.0.140", features = ["derive"] }
bitvec = { version = "^1.0.1", features = ["serde"] }
lazy_static = "^1.4.0"
console_error_panic_hook = "0.1"

[build-dependencies]
embed-resource = "^1.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

members = ["bo_logging", "bo_pathfinding"]
