[package]
edition = "2021"
name = "bload_oath"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["debug"]
debug = []

[dependencies]
bracket-lib = { version = "~0.8.1", features = ["serde"] }
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }

lazy_static = "1.4.0"
parking_lot = { version = "0.12.1", features = ["nightly"] }

[build-dependencies]
embed-resource = "1.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
