[package]
edition = "2021"
name = "bload_oath"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["debug"]
debug = []

[dependencies]
bo_ecs = { path = "bo_ecs/" }
bo_map = { path = "bo_map/" }
bo_utils = { path = "bo_utils/" }
bo_logging = { path = "bo_logging/" }

bracket-lib = { version = "~0.8.1", features = ["serde"] }
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [
  "dynamic",
] }

iyes_loopless = { git = "https://github.com/iyesgames/iyes_loopless", branch = "bevy_main" }

lazy_static = "1.4.0"
parking_lot = { version = "0.12.1", features = ["nightly"] }
rayon = "~1.5.3"
bitvec = "^1.0.1"

[build-dependencies]
embed-resource = "1.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

members = ["bo_map", "bo_ecs", "bo_utils", "bo_logging"]
