[package]
edition = "2021"
name = "bload_oath"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["debug"]
debug = []

[dependencies]
bracket-lib = { version = "~0.8.1", features = ["serde"] }
bevy = { version = "~0.7.0", default-features = false, features = ["dynamic"] }
iyes_loopless = "~0.6.1"
rayon = "~1.5.3"

lazy_static = "1.4.0"
parking_lot = { version = "0.12.1", features = ["nightly"] }
bitvec = "~1.0.1"

[build-dependencies]
embed-resource = "1.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
