[package]
edition = "2021"
name = "bload_oath"
version = "0.1.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["bevy/dynamic", "bracket-lib/threaded"]
dev = ["bevy/dynamic"]
web = []

[dependencies]
bo_logging = { path = "bo_logging/" }
bo_pathfinding = { path = "bo_pathfinding/" }

# Core Crates
bracket-lib = { git = "https://github.com/lecoqjacob/bracket-lib", branch = "custom", features = [
  "serde",
  "bevy",
] }

iyes_loopless = "~0.7.0"
bevy = { version = "~0.8.0", default-features = false }

# Utility Crates
parking_lot = { version = "^0.12.1", features = ["nightly"] }
serde = { version = "^1.0.140", features = ["derive"] }
bitvec = { version = "^1.0.1", features = ["serde"] }
lazy_static = "^1.4.0"
console_error_panic_hook = "0.1"
ron = "^0.7.1"

[build-dependencies]
embed-resource = "^1.7.3"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

members = ["bo_logging", "bo_pathfinding"]
